name: Test

on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.18"

      - name: Lint with golangci-lint
        uses: golangci/golangci-lint-action@v3

      - name: Lint with gofmt and go vet
        run: |
          gofmt -l -e .
          go vet ./...

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.18"

      - name: Test
        run: |
          go test -race ./...
